export default function KeyValueRow(props) {
    return React.createElement(
        "tr",
        null,
        React.createElement(
            "td",
            null,
            props.id
        ),
        React.createElement(
            "td",
            null,
            props.dataKey
        ),
        React.createElement(
            "td",
            null,
            props.value
        ),
        React.createElement(
            "td",
            null,
            props.expire_on
        ),
        React.createElement(
            "td",
            null,
            React.createElement(
                "button",
                null,
                ":)"
            )
        )
    );
}